//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cCar()
        {
            this.vRepair = new HashSet<vRepair>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public string Brand_Model { get; set; }
        public int IDOwner { get; set; }
    
        public virtual cClient cClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vRepair> vRepair { get; set; }
    }
}
