//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STOEntities : DbContext
    {
        public STOEntities()
            : base("name=STOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cCar> cCar { get; set; }
        public virtual DbSet<cClient> cClient { get; set; }
        public virtual DbSet<cDetail> cDetail { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vRepair> vRepair { get; set; }
        public virtual DbSet<vUsed_Detail> vUsed_Detail { get; set; }
        public virtual DbSet<wView> wView { get; set; }
    }
}
