//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRepair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vRepair()
        {
            this.vUsed_Detail = new HashSet<vUsed_Detail>();
        }
    
        public int ID { get; set; }
        public string Reason_of_problem { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public Nullable<System.DateTime> Guarantee { get; set; }
        public decimal Price { get; set; }
        public int Car_ID { get; set; }
        public int Client_ID { get; set; }
    
        public virtual cCar cCar { get; set; }
        public virtual cClient cClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vUsed_Detail> vUsed_Detail { get; set; }
    }
}
