//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUsed_Detail
    {
        public int ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Detail_ID { get; set; }
        public int Repair_ID { get; set; }
    
        public virtual cDetail cDetail { get; set; }
        public virtual vRepair vRepair { get; set; }
    }
}
