//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO
{
    using System;
    using System.Collections.Generic;
    
    public partial class wView
    {
        public string Client { get; set; }
        public string Number { get; set; }
        public string Car_brand { get; set; }
        public string Detail { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Reason_of_problem { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Available_Amount { get; set; }
    }
}
